# GitHub Pages Configuration
title: "Destiny 2 Helpful Tips"
description: "Comprehensive guides for Destiny 2 raids, dungeons, and resources"

# Use a GitHub Pages supported theme
theme: minima

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-relative-links

# Enable relative links processing
relative_links:
  enabled: true
  collections: false

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Set the base URL (leave empty for GitHub Pages)
baseurl: ""
url: ""

# Minima theme customization
minima:
  skin: dark

# Custom variables for dark theme
sass:
  style: compressed
